# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = "3.10"

_lr_method = "LALR"

_lr_signature = (
    "ASSIGN COMMA ID LBRACE LSQUARE RBRACE RSQUARE TYPE\n    expression : ID ASSIGN type\n    \n    type : TYPE\n    \n"
    "    type : TYPE LSQUARE RSQUARE\n    expression : expression COMMA expressionexpression : LBRACE expression RBRACE"
)

_lr_action_items = {
    "ID": (
        [
            0,
            3,
            4,
        ],
        [
            2,
            2,
            2,
        ],
    ),
    "LBRACE": (
        [
            0,
            3,
            4,
        ],
        [
            3,
            3,
            3,
        ],
    ),
    "$end": (
        [
            1,
            7,
            8,
            9,
            10,
            12,
        ],
        [
            0,
            -4,
            -1,
            -2,
            -5,
            -3,
        ],
    ),
    "COMMA": (
        [
            1,
            6,
            7,
            8,
            9,
            10,
            12,
        ],
        [
            4,
            4,
            4,
            -1,
            -2,
            -5,
            -3,
        ],
    ),
    "ASSIGN": (
        [
            2,
        ],
        [
            5,
        ],
    ),
    "TYPE": (
        [
            5,
        ],
        [
            9,
        ],
    ),
    "RBRACE": (
        [
            6,
            7,
            8,
            9,
            10,
            12,
        ],
        [
            10,
            -4,
            -1,
            -2,
            -5,
            -3,
        ],
    ),
    "LSQUARE": (
        [
            9,
        ],
        [
            11,
        ],
    ),
    "RSQUARE": (
        [
            11,
        ],
        [
            12,
        ],
    ),
}

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if _x not in _lr_action:
            _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {
    "expression": (
        [
            0,
            3,
            4,
        ],
        [
            1,
            6,
            7,
        ],
    ),
    "type": (
        [
            5,
        ],
        [
            8,
        ],
    ),
}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if _x not in _lr_goto:
            _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> expression", "S'", 1, None, None, None),
    ("expression -> ID ASSIGN type", "expression", 3, "p_expression", "parser.py", 42),
    ("type -> TYPE", "type", 1, "p_type", "parser.py", 49),
    ("type -> TYPE LSQUARE RSQUARE", "type", 3, "p_type_array", "parser.py", 56),
    ("expression -> expression COMMA expression", "expression", 3, "p_expression_comma", "parser.py", 62),
    ("expression -> LBRACE expression RBRACE", "expression", 3, "p_expression_group", "parser.py", 67),
]
